package main

import "fmt"

func printBanner() {
  fmt.Print(ColorCyan)
  fmt.Println("██╗   ██╗██╗   ██╗██╗      ██████╗ █████╗ ███╗   ██╗███████╗██╗   ██╗███████╗")
  fmt.Println("██║   ██║██║   ██║██║     ██╔════╝██╔══██╗████╗  ██║██╔════╝╚██╗ ██╔╝██╔════╝")
  fmt.Println("██║   ██║██║   ██║██║     ██║     ███████║██╔██╗ ██║█████╗   ╚████╔╝ █████╗  ")
  fmt.Println("╚██╗ ██╔╝██║   ██║██║     ██║     ██╔══██║██║╚██╗██║██╔══╝    ╚██╔╝  ██╔══╝  ")
  fmt.Println(" ╚████╔╝ ╚██████╔╝███████╗╚██████╗██║  ██║██║ ╚████║███████╗   ██║   ███████╗")
  fmt.Println("  ╚═══╝   ╚═════╝ ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚══════╝")
  fmt.Println()
  fmt.Println("              Web Vulnerability Scanner by Xwal13")
  fmt.Print(ColorReset)
}

func printUsage() {
	printBanner()
	fmt.Println()
	fmt.Println("Usage: VulcanEye -u <url> [options]")
	fmt.Println()
	fmt.Println("Main options:")
	fmt.Println("  -u string              Target URL to scan (required)")
	fmt.Println("  -m string              HTTP method (GET or POST) (default \"GET\")")
	fmt.Println("  -p string              Parameter name to inject (auto-detect if omitted)")
	fmt.Println("  -cookie string         Cookie header for authenticated scans")
	fmt.Println("  -o string              Output file to save results")
	fmt.Println("  -d                     Enable debug mode")
	fmt.Println("  -crawl int             Crawl depth (default 1)")
	fmt.Println("  -rate int              Max requests per second (default 10, 0 = unlimited)")
	fmt.Println()
	fmt.Println("Output & Integration:")
	fmt.Println("  -format string         Output format: text, json, or xml (default \"text\")")
	fmt.Println("  -proxy string          HTTP proxy URL (e.g., http://127.0.0.1:8080 for Burp/ZAP)")
	fmt.Println("  -agent string          Custom User-Agent header")
	fmt.Println("  -hdr string            Custom header (format: \"Name: Value\")")
	fmt.Println("  -log string            Log file for request/response details")
	fmt.Println("  -elog string           Error log file for warnings and errors")
	fmt.Println("  -verify                Verify findings by re-testing them (reduces false positives)")
	fmt.Println()
	fmt.Println("Vulnerability Scans:")
	fmt.Println("  -x                     Cross-Site Scripting (XSS)")
	fmt.Println("  -s                     SQL Injection (SQLi) - error, boolean, time-based")
	fmt.Println("  -l                     Local File Inclusion (LFI)")
	fmt.Println("  -r                     Remote Code Execution (RCE)")
	fmt.Println("  -or                    Open Redirect")
	fmt.Println("  -pt                    Path Traversal")
	fmt.Println("  -csrf                  Cross-Site Request Forgery (CSRF)")
	fmt.Println("  -ssrf                  Server-Side Request Forgery (SSRF)")
	fmt.Println("  -ssti                  Server-Side Template Injection (SSTI)")
	fmt.Println("  -nosql                 NoSQL Injection")
	fmt.Println("  -xxe                   XML External Entity (XXE)")
	fmt.Println("  -header                Header Injection (CRLF)")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  VulcanEye -u \"http://target.com/page.php?id=1\" -x")
	fmt.Println("  VulcanEye -u \"http://target.com/\" -m POST -cookie \"PHPSESSID=abc\"")
	fmt.Println("  VulcanEye -u \"http://target.com/\" -x -s -l")
	fmt.Println("  VulcanEye -u \"http://target.com/\" -format json -o results.json")
	fmt.Println("  VulcanEye -u \"http://target.com/\" -verify -log requests.log")
	fmt.Println("  VulcanEye -u \"http://target.com/\" -proxy http://127.0.0.1:8080")
	fmt.Println()
	fmt.Println("Note: If no scan type is specified, all vulnerability scans are performed by default.")
}